name: 'Gemini AI Code Review'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get Pull Request Diff'
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff_content<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Call Gemini for Review'
        id: gemini_review
        run: |
          PROMPT="Você é um revisor de código sênior, especialista em Dart e Flutter. Sua tarefa é revisar o seguinte diff de um Pull Request.
          
          Regras da revisão:
          1. Foque em potenciais bugs, problemas de performance, e desvios das boas práticas do Flutter (ex: 'const' em widgets, estado imutável).
          2. Seja conciso e direto.
          3. Se não houver problemas, apenas responda 'O código parece bom, nenhuma sugestão.'
          4. Formate sua resposta em Markdown.
          
          Aqui está o diff para revisar:
          \`\`\`diff
          ${{ steps.get_diff.outputs.diff_content }}
          \`\`\`"
          
          JSON_PAYLOAD=$(jq -n --arg prompt "$PROMPT" \
            '{ "contents": [ { "parts": [ { "text": $prompt } ] } ] }')

          API_RESPONSE=$(curl -s -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://generativelenlanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.GEMINI_API_KEY }}")
            
          REVIEW_COMMENT=$(echo $API_RESPONSE | jq -r '.candidates[0].content.parts[0].text')
          
          echo "review_comment<<EOF" >> $GITHUB_OUTPUT
          echo "$REVIEW_COMMENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: 'Comment on Pull Request'
        uses: actions/github-script@v7
        with:
          script: |
            const reviewComment = `${{ steps.gemini_review.outputs.review_comment }}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### 🤖 Revisão de Código pelo Gemini AI\n\n${reviewComment}`
            });
