name: 'Gemini AI Code Review'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get Pull Request Diff'
        id: get_diff
        run: |
          DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "diff_content<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

     - name: 'Call Gemini for Review'
        id: gemini_review
        run: |
          # Esta nova versão constrói o payload JSON de forma mais segura para evitar
          # erros com caracteres especiais no diff do código.
          JSON_PAYLOAD=$(jq -n --arg diff_content "${{ steps.get_diff.outputs.diff_content }}" '{
            "contents": [{
              "parts": [{
                "text": "Você é um revisor de código sênior, especialista em Dart e Flutter. Sua tarefa é revisar o seguinte diff de um Pull Request.\n\nRegras da revisão:\n1. Foque em potenciais bugs, problemas de performance, e desvios das boas práticas do Flutter (ex: \"const\" em widgets, estado imutável).\n2. Seja conciso e direto.\n3. Se não houver problemas, apenas responda \"O código parece bom, nenhuma sugestão.\".\n4. Formate sua resposta em Markdown.\n\nAqui está o diff para revisar:\n```diff\n" + $diff_content + "\n```"
              }]
            }]
          }')

          API_RESPONSE=$(curl -s -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=${{ secrets.GEMINI_API_KEY }}")
            
          REVIEW_COMMENT=$(echo "$API_RESPONSE" | jq -r ".candidates[0].content.parts[0].text")
          
          echo "review_comment<<EOF" >> "$GITHUB_OUTPUT"
          echo "$REVIEW_COMMENT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: 'Comment on Pull Request'
        uses: actions/github-script@v7
        with:
          script: |
            const reviewComment = `${{ steps.gemini_review.outputs.review_comment }}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### 🤖 Revisão de Código pelo Gemini AI\n\n${reviewComment}`
            });
